interactions:
- request:
    body: '{"username": "FOOBAR", "password": "FAKE"}'
    headers:
      Accept:
      - '*/*'
      Accept-Encoding:
      - gzip, deflate
      Connection:
      - keep-alive
      Content-Length:
      - '53'
      Content-Type:
      - application/json; charset=utf-8
      User-Agent:
      - python-requests/2.28.0
    method: POST
    uri: https://help.uillinois.edu/SBTDWebApi/api/auth
  response:
    body:
      string: ''
    headers:
      Cache-Control:
      - no-cache
      Content-Length:
      - '0'
      Date:
      - Tue, 28 Jun 2022 16:55:40 GMT
      Expires:
      - '-1'
      Pragma:
      - no-cache
      X-RateLimit-Limit:
      - '60'
      X-RateLimit-Remaining:
      - '59'
      X-RateLimit-Reset:
      - Tue, 28 Jun 2022 16:56:41 GMT
      X-TDX-Partition:
      - '26'
      X-TDX-TraceID:
      - 0d4d5135-7bba-4226-b473-bda224386b01
      X-UA-Compatible:
      - IE=edge
    status:
      code: 400
      message: Bad Request
version: 1
