# Based on techservicesillinois/splunk-soar-template
# Adds TAR file as a release asset
name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - edited
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v2
    - name: Virtual Env
      run: |
        make venv
    - name: Linter
      run: |
        make lint
    - name: Static checks
      run: |
        make static 
    - name: Tests
      run: |
        make test
    - name: Build Package (Prod)
      if: github.event_name == 'release'
      run: |
        make build
    - name: Build Package (Test)
      if: github.event_name == 'pull_request'
      run: |
        make build-test
    - name: Store build as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: deployed tar file
        path: app.tar
        retention-days: 7
    - name: Post to Splunk SOAR API
      if: github.event_name == 'release' && github.event.action != 'prereleased' || github.event_name == 'pull_request'
      run: |
        make deploy
      env:
        SOAR_TOKEN: ${{ secrets.SOAR_TOKEN }}
        SOAR_HOSTNAME: ${{ secrets.SOAR_HOSTNAME }}
    - name: Get Current Release
      id: get_current_release
      uses: joutvhu/get-release@v1
      with:
        debug: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Release Asset
      if: github.event_name == 'release'
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_current_release.outputs.upload_url }} 
        asset_path: app.tar
        asset_name: soar-tdx-app.tar
        asset_content_type: application/zip
